/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesNameRouteImport } from './routes/templates/$name'
import { Route as CategoriesNameRouteImport } from './routes/categories/$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesNameRoute = TemplatesNameRouteImport.update({
  id: '/templates/$name',
  path: '/templates/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesNameRoute = CategoriesNameRouteImport.update({
  id: '/categories/$name',
  path: '/categories/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories/$name': typeof CategoriesNameRoute
  '/templates/$name': typeof TemplatesNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories/$name': typeof CategoriesNameRoute
  '/templates/$name': typeof TemplatesNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categories/$name': typeof CategoriesNameRoute
  '/templates/$name': typeof TemplatesNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/categories/$name' | '/templates/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/categories/$name' | '/templates/$name'
  id: '__root__' | '/' | '/categories/$name' | '/templates/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesNameRoute: typeof CategoriesNameRoute
  TemplatesNameRoute: typeof TemplatesNameRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$name': {
      id: '/templates/$name'
      path: '/templates/$name'
      fullPath: '/templates/$name'
      preLoaderRoute: typeof TemplatesNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$name': {
      id: '/categories/$name'
      path: '/categories/$name'
      fullPath: '/categories/$name'
      preLoaderRoute: typeof CategoriesNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesNameRoute: CategoriesNameRoute,
  TemplatesNameRoute: TemplatesNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
