name: Test & Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-build:
    name: Test & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24.2'

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '>22'
          cache: 'pnpm'
          cache-dependency-path: 'web/pnpm-lock.yaml'

      - name: Install web dependencies
        working-directory: ./web
        run: pnpm install --frozen-lockfile

      - name: Build web 
        working-directory: ./web
        run: pnpm build

      - name: Check dist
        run: ls -la web/dist

      - name: Download Go dependencies
        run: go mod download

      - name: Run Go tests
        run: go test -v ./...

      - name: Build binary
        run: make build

      - name: Verify binary
        run: ./kite --help
